### ISSUE TITLE
Attachment new features

### ISSUE THREAD

**Issue by NaveenRayappan** [NaveenRayappan1808/WhatsappWorld#1]
Hi Naveen1808,
  I have reviewed your Whatsappworld code in that  You can enhance your product like attach pdf, documents and excel type files.
Thanks,
Naveen be Cse

**Comment by NaveenRayappan1808** [comment]
ok NaveenBe cse. I will review the code and let you know soon.

**Comment by NaveenRayappan1808** [comment]
Hey, Naveen be cse ,
   I have added your enhancement features and it is worked for me successfully. Thanks,
